name: itemauthentication
main: com.hackthedoc.itemauthentication.ItemAuthenticationPlugin
version: 0.0.6
api-version: 1.21
description: "Unique Item Authentication system"
commands:
  authenticate:
    description: "Authenticate the object hold by the player"
    usage: "/authenticate"
    permission: itemauthentication.use
permissions:
  itemauthentication.use:
    description: "Allow players to use command /authenticate"
    default: true
depend:
  - Vault