name: itemauthentification
main: com.hackthedoc.itemauthentification.ItemAuthentificationPlugin
version: 0.0.5
api-version: 1.21
description: "Unique Item Authentification system"
commands:
  authentificate:
    description: "Authentificate the object hold by the player"
    usage: "/authentificate"
    permission: itemauthentification.use
permissions:
  itemauthentification.use:
    description: "Allow players to use command /authenficate"
    default: true
depend:
  - Vault